# Default values for sonarr

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: linuxserver/sonarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Etc/UTC"

service:
  type: ClusterIP
  port: 8989

ingress:
  enabled: false
  className: ""
  annotations: {}
  host: sonarr.local
  tls:
    enabled: false
    secretName: sonarr-tls

persistence:
  config:
    enabled: true
    size: 1Gi
    storageClass: ""
    existingClaim: ""  # Use existing PVC instead of creating a new one
  

  media:
    enabled: false
    size: 100Gi
    storageClass: ""
    existingClaim: ""  # Use existing PVC instead of creating a new one
    subPath: ""        # Subpath within the PVC

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /
    port: 8989
  initialDelaySeconds: 60
  periodSeconds: 30
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 8989
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

podSecurityContext: {}
  # fsGroup: 1000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

serviceAccount:
  create: true
  annotations: {}
  name: ""

nodeSelector: {}

tolerations: []

affinity: {}