# Jellyseerr Values for Testing
# Media request and discovery tool for Jellyfin and Plex

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: fallenbagel/jellyseerr
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5055

ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
  hosts:
    - host: jellyseerr.dev.cubancodelab.net
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  config:
    enabled: true
    storageClass: "nfs-ssd-fast"
    accessMode: ReadWriteOnce
    size: 2Gi

env:
  LOG_LEVEL: "info"
  TZ: "America/Havana"
  PORT: "5055"

extraEnv: []

securityContext:
  runAsUser: 999
  runAsGroup: 999
  runAsNonRoot: true

podSecurityContext:
  fsGroup: 999

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

healthChecks:
  liveness:
    enabled: true
    httpGet:
      path: /api/v1/status
      port: http
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    httpGet:
      path: /api/v1/status
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  
  startup:
    enabled: true
    httpGet:
      path: /api/v1/status
      port: http
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 15
    successThreshold: 1

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podDisruptionBudget:
  enabled: false
  minAvailable: 1