apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qbittorrent.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qbittorrent.labels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent.serviceAccountName" . }}
      containers:
      # Main qBittorrent Container
      - name: qbittorrent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: webui
          containerPort: {{ .Values.env.WEBUI_PORT }}
        - name: torrenting-tcp
          containerPort: 6881
          protocol: TCP
        - name: torrenting-udp
          containerPort: 6881
          protocol: UDP
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.env.WEBUI_PORT }}
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.env.WEBUI_PORT }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /config
        {{- if .Values.persistence.downloads.enabled }}
        - name: downloads
          mountPath: /downloads
          {{- if .Values.persistence.downloads.subPath }}
          subPath: {{ .Values.persistence.downloads.subPath }}
          {{- end }}
        {{- end }}
      volumes:
      - name: config
        {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "qbittorrent.configPVCName" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.persistence.downloads.enabled }}
      - name: downloads
        persistentVolumeClaim:
          claimName: {{ include "qbittorrent.downloadsPVCName" . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}