apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zero-api.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "zero-api.labels" . | nindent 4 }}
data:
  USE_ACTUAL_BUDGET: {{ .Values.config.useActualBudget | quote }}
