{{- if eq .Values.secrets.management "create" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-api.fullname" . }}-secrets
  namespace: {{ include "zero-api.namespace" . }}
  labels:
    {{- include "zero-api.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
{{- if .Values.secrets.data }}
stringData:
  {{- if .Values.secrets.data.actualServerUrl }}
  ACTUAL_SERVER_URL: {{ .Values.secrets.data.actualServerUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.data.actualPassword }}
  ACTUAL_PASSWORD: {{ .Values.secrets.data.actualPassword | quote }}
  {{- end }}
  {{- if .Values.secrets.data.actualBudgetId }}
  ACTUAL_BUDGET_ID: {{ .Values.secrets.data.actualBudgetId | quote }}
  {{- end }}
{{- else }}
data: {}
{{- end }}
{{- end }}