apiVersion: v1
kind: Service
metadata:
  name: {{ include "prowlarr.fullname" . }}
  labels:
    {{- include "prowlarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9696
      protocol: TCP
  selector:
    {{- include "prowlarr.labels" . | nindent 4 }}