{{- if .Values.password.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole.fullname" . }}-secret
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.password.value | b64enc | quote }}
{{- end }}