apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-web
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    {{- include "pihole.selectorLabels" . | nindent 4 }}