apiVersion: v2
name: jellyseerr
description: A Helm chart for Jellyseerr - media request and discovery tool
type: application
version: 0.1.0
appVersion: "latest"
home: https://github.com/Fallenbagel/jellyseerr
sources:
  - https://github.com/Fallenbagel/jellyseerr
maintainers:
  - name: homelab-charts
keywords:
  - media
  - jellyfin
  - plex
  - requests
  - discovery