# Jellyseerr Values
# Media request and discovery tool for Jellyfin and Plex

nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  repository: fallenbagel/jellyseerr
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5055

ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: "letsencrypt-staging"
    # traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
  hosts:
    - host: jellyseerr.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

persistence:
  config:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 1Gi

env:
  LOG_LEVEL: "info"
  TZ: "UTC"
  PORT: "5055"

extraEnv: []

securityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
  runAsNonRoot: true

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

healthChecks:
  liveness:
    enabled: true
    httpGet:
      path: /api/v1/status
      port: http
    initialDelaySeconds: 60
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readiness:
    enabled: true
    httpGet:
      path: /api/v1/status
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1
  
  startup:
    enabled: true
    httpGet:
      path: /api/v1/status
      port: http
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 15
    successThreshold: 1

nodeSelector: {}
tolerations: []
affinity: {}

podAnnotations: {}
podSecurityContext: {}

serviceAccount:
  create: false
  annotations: {}
  name: ""

podDisruptionBudget:
  enabled: false
  minAvailable: 1