apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaresolverr.fullname" . }}
  labels:
    {{- include "flaresolverr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "flaresolverr.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "flaresolverr.labels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "flaresolverr.serviceAccountName" . }}
      containers:
      - name: flaresolverr
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8191
          protocol: TCP
        env:
        - name: LOG_LEVEL
          value: {{ .Values.env.LOG_LEVEL | quote }}
        - name: BROWSER_TIMEOUT
          value: {{ .Values.env.BROWSER_TIMEOUT | quote }}
        - name: TEST_URL
          value: {{ .Values.env.TEST_URL | quote }}
        - name: PORT
          value: {{ .Values.env.PORT | quote }}
        {{- if .Values.env.CAPTCHA_SOLVER }}
        - name: CAPTCHA_SOLVER
          value: {{ .Values.env.CAPTCHA_SOLVER | quote }}
        {{- end }}
        {{- if .Values.env.CAPTCHA_SOLVER_KEY }}
        - name: CAPTCHA_SOLVER_KEY
          value: {{ .Values.env.CAPTCHA_SOLVER_KEY | quote }}
        {{- end }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- if .Values.persistence.tmp.enabled }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- end }}
      {{- if .Values.persistence.tmp.enabled }}
      volumes:
      - name: tmp
        {{- if .Values.persistence.tmp.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "flaresolverr.tmpPVCName" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}