apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazarr.fullname" . }}
  labels:
     {{- include "bazarr.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bazarr.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
         {{- include "bazarr.labels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bazarr.serviceAccountName" . }}
      containers:
      - name: bazarr
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 6767
        env:
        - name: PUID
          value: {{ .Values.env.PUID | quote }}
        - name: PGID
          value: {{ .Values.env.PGID | quote }}
        - name: TZ
          value: {{ .Values.env.TZ | quote }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /config
        {{- if .Values.persistence.media.enabled }}
        - name: media
          mountPath: /media
          {{- if .Values.persistence.media.subPath }}
          subPath: {{ .Values.persistence.media.subPath }}
          {{- end }}
        {{- end }}


      volumes:
      - name: config
        {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "bazarr.configPVCName" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
      {{- if .Values.persistence.media.enabled }}
      - name: media
        {{- if .Values.persistence.media.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.media.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "bazarr.fullname" . }}-media
        {{- end }}
      {{- end }}
            {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        