name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Create gh-pages branch if needed
        run: |
          if ! git ls-remote --exit-code origin gh-pages >/dev/null 2>&1; then
            echo "Creating gh-pages branch..."
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# Helm Charts Repository" > index.html
            git add index.html
            git commit -m "Initial gh-pages commit"
            git push origin gh-pages
            git checkout main
          fi

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy to GitHub Pages
        run: |
          git fetch origin gh-pages 2>/dev/null || true
          if git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout gh-pages
            git reset --hard origin/gh-pages 2>/dev/null || git reset --hard HEAD
          else
            git checkout --orphan gh-pages
          fi
          ./generate-pages-readme.sh > README.md
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "docs: update repository documentation"
            git push origin gh-pages --force
          fi
